import { create } from "zustand";

export const useDataStore = create((set) => ({
  career: null,
  careerDetail: null,
  users: null,
  sraInfo: null,
  ptInfo: null,
  myTest: null,
  careerList: null,
  careerSubList: null,
  counselorHome: null,
  searchCounselors: null,
  searchCareer: null,
  searchCourses: null,
  courses: null,
  courseId: null,
  buyCourse: null,
  service: null,
  policy: null,
  term: null,
  about: null,
  moment: null,
  stories: null,
  seoData: null,
  careerGenz: null,
  zcourseId: null,
  counselorPopup: null,

  setSearchCounselors: (e) => set({ searchCounselors: e }),
  setSearchCareer: (e) => set({ searchCareer: e }),
  setSearchCourses: (e) => set({ searchCourses: e }),
  setCounselorPopup: (e) => set({ counselorPopup: e }),
  setZcourseId: (e) => set({ zcourseId: e }),
  setCareerGenz: (e) => set({ careerGenz: e }),
  setSeodata: (e) => set({ seoData: e }),
  setHomeCareer: (e) => set({ homeCareer: e }),
  setStories: (e) => set({ stories: e }),
  setMoment: (e) => set({ moment: e }),
  setAbout: (e) => set({ about: e }),
  setPoliocy: (e) => set({ policy: e }),
  setTerm: (e) => set({ term: e }),
  setService: (e) => set({ service: e }),
  setCourseId: (e) => set({ courseId: e }),
  setMytest: (e) => set({ myTest: e }),
  setCaree: (e) => set({ career: e }),
  setCareerDetail: (e) => set({ careerDetail: e }),
  setCareerList: (e) => set({ careerList: e }),
  setCareerSubList: (e) => set({ careerSubList: e }),
  setUsers: (e) => set({ users: e }),
  setSraInfo: (e) => set({ sraInfo: e }),
  setPtinfo: (e) => set({ ptInfo: e }),
  setCourses: (e) => set({ courses: e }),
  setcounselorHome: (e) => set({ counselorHome: e }),
  setBuyCourse: (e) => set({ buyCourse: e }),
}))